on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-last-updated:
    if: github.actor == 'plibither8'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update last updated date
        run: |
          LAST_UPDATED=$(git log -1 --format=%cd --date=format:"%B %Y")
          sed -i static/resume.yaml -e "s/lastUpdated:.*/lastUpdated: $LAST_UPDATED/"
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[bot] Update "Last updated" date'
          commit_user_name: plibother8
          commit_user_email: bot@mihir.ch
          commit_author: plibother8 <bot@mihir.ch>
