# Update date on every commit
on:
  push:
    branches:
      - main

jobs:
  update-last-updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get last updated date
        run: echo "LAST_UPDATED=$(git log -1 --format=%cd --date=format:"%B %Y")" >> $GITHUB_ENV
      - name: Update resume.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: static/resume.yaml
          propertyPath: meta.lastUpdated
          value: ${{ env.LAST_UPDATED }}
          commitChange: true
          message: '[bot] [skip ci] Update "Last updated" date'
          branch: main
          masterBranchName: main
          commitUserName: plibother8
          commitUserEmail: bot@mihir.ch
          token: ${{ secrets.BOT_PAT }}
